name: pilot-development

channels:
  - diracgrid
  - conda-forge
  - defaults

dependencies:
  # runtime
  - python =3.8
  - pip
  - requests
  - stomp.py
  # testing and development
  - autopep8
  - caniusepython3
  - coverage
  - mock
  - pylint
  - pytest >=3.6
  - pytest-mock
  - shellcheck
